name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }} # Nom du registy
  IMAGE_NAME: "backend-app" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ env.REGISTRY }} \
          -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} ./backend

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}