name: CI Backend - Build & Push to ACR

on:
  push:
    branches:
      - main
    paths:
      - "src/backend/**"
      - ".github/workflows/ci-backend.yml"

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }} # ex: monregistry.azurecr.io
  IMAGE_NAME: backend-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ env.REGISTRY }}" \
            -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./src/backend

      - name: Push Docker image
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"